stages:
    - format
    - test

before_script:
   - python -V
   - python -m venv venv
   - source venv/bin/activate
   - pip install -U pip
   - pip install .[tests]

format:py37:
    image: python:3.7
    stage: format
    script:
        - pytest -m format

unit_test:py37:
    image: python:3.7
    stage: test
    script:
        - pytest -m unit --durations 10


format:py38:
    image: python:3.8
    stage: format
    script:
        - pytest -m format

unit_test:py38:
    image: python:3.8
    stage: test
    script:
        - pytest -m unit --durations 10
